### ISSUE TITLE
issue with collaboration 

### ISSUE THREAD

**Issue by LeonFedotov** [alswl/excalidraw-collaboration#21]
layering doesn't always work 
add three elements one on top of the other
right click on the top one and send to back 
this doesnt update the view and doesnt always sends the element to the back

**Comment by alswl** [comment]
Can you try on the upstream website https://excalidraw.com/ ? This repo is a extension of self-host, it did not modified the original panting feature.

and could you provide more informations, like capture or recording?

**Comment by matbgn** [comment]
I've got also some issues with collaboration and as @LeonFedotov gives no more answer I take the opportunity for this issue to be closed, that's the reason why I follow up here:

I have some CORS problem with storage in front of a Caddy proxy that could correctly get TLS certificates, here the console logs: 

Access to fetch at 'https://whiteboard-storage.***.com/api/v2/rooms/ebe6dd121ec8e27bca12' from origin 'https://whiteboard.***.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Here my yaml:

```
services:
  frontend:
    image: alswl/excalidraw:v0.17.0-fork-b1 # <==== SAME FOR b2 BTW
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://whiteboard.***.com/api/v2/
      - VITE_APP_BACKEND_V2_POST_URL=https://whiteboard.***.com/api/v2/post/
      - VITE_APP_WS_SERVER_URL=https://whiteboard-room.***.com
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://whiteboard-storage.***.com/api/v2
      - VITE_APP_STORAGE_BACKEND=http
    ports:
      - 8880:80
  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: always
    environment:
      # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
      - PORT=8881
    ports:
      - 8881:8081
  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    ports:
      - 8882:80
networks: {}
```

Any clue?
