### ISSUE TITLE
help setting up external acess with https

### ISSUE THREAD

**Issue by otomay** [alswl/excalidraw-collaboration#22]
I'm trying to setup an colab server with external access, but I'm feeling lost rn hehehe
Saw all issues, but none of them helped me (っ˘̩╭╮˘̩)っ

I'm facing two errors in the browser console:

- 1: Could not connect to websocket
- 2: Could not find API path (maybe bc of the ws? or ws not working bc api? idk)

I don't understand why the API is not working, even without my domain. Shouldn't I see something in the browser when I explore, for example: `ip:port/api/v2` ?

Anyway, my current setup is as follows:

### docker-compose (pls see the # coments):
```
services:
  frontend:
    image: excalidraw:v0.1.0-b35a2c3-dirty
    ports:
      - 4321:80

  storage:
    image: excalidraw-storage-backend:v0.1.0-b35a2c3-dirty
    restart: always
    environment:
      - PORT=8081 # this should be the same port? I didn't understand that option, mainly because on https://github.com/alswl/excalidraw-storage-backend/tree/e3219306d1ef8db6981e4918d73a3c957c025340#environement-variables it says that the default port is 8080 but in the example you showed the same
      - STORAGE_URI=mysql://user:pass@@10.0.0.217:3306/excalidraw # working just fine (user/pass censored)
    ports:
      - 8081:8081 # when i access ip:8081/api/v2 I see 404 not found

  room:
    image: excalidraw-room:v0.1.0-b35a2c3-dirty
    ports:
      - 8082:80 # when i access ip:8082 I see a small text saying the colab server is running (✿◠‿◠)
```

So, I got nginx set to port 4321. Like `https://excalidraw.mydomain.com.br`. It works fine.
nginx set to port 8081 also. Like `https://excalidrawbd.mydomain.com.br`. The api path does not work either.
And I got nginx set to port 8082. Like `https://excalidrawws.mydomain.com.br`. It works fine.

### .env (pls see the # coments):

```
REACT_APP_BACKEND_V2_GET_URL=https://test.com/api/v2/
REACT_APP_BACKEND_V2_POST_URL=https://test.com/api/v2/post/

REACT_APP_LIBRARY_URL=https://libraries.excalidraw.com
REACT_APP_LIBRARY_BACKEND=https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries

REACT_APP_HTTP_STORAGE_BACKEND_URL=excalidrawbd.mydomain.com.br/api/v2 # dummy domain (censored mine)
REACT_APP_STORAGE_BACKEND=http

REACT_APP_PORTAL_URL= #should I set something here? IDK if the comments belo are for REACT_APP_WS_SERVER_URL or for REACT_APP_PORTAL_URL
# Fill to set socket server URL used for collaboration.
# Meant for forks only: excalidraw.com uses custom REACT_APP_PORTAL_URL flow
REACT_APP_WS_SERVER_URL=https://excalidrawws.mydomain.com.br. # tried also to put nginx domain like https://excalidraw.mydomain.com.br and ip:8082. Same results.

REACT_APP_FIREBASE_CONFIG='{}'

# production-only vars
REACT_APP_GOOGLE_ANALYTICS_ID=foo

REACT_APP_PLUS_APP=https://app.excalidraw.com
```

I saw you mentioning port 443 here: https://github.com/alswl/excalidraw-collaboration/issues/5#issuecomment-1400414775 and I think I have the same problem, but have no ideia how to solve it. My nginx config already have the 443:443 configuration. Already joined the 3 containers on nginx network and... stil nothing.

The browser error:
![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/49d26fe8-4305-4cbc-b9db-cd62f93f0ff6)

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/45b43a5f-9168-4e04-b459-cc58c7e998cd)

pls help (╥_╥)

**Comment by agrimpelhuber** [comment]
@otomay, just wanted to say that I'm planning to do the same (external access), so I'll post any findings here as I find the time to get it up and running. Here's the plan, and even though I do it with Traefik as a Reverse Proxy / Edge Router, the principle should be the same:

Most important: In the end, Nginx will serve all three containers (App, Websocket and Storage) **on the same port 443, under the same domain, with the same TLS certificate**, so they'll be all in the same Nginx "server" section. I hope I'm not stating the obvious (if so, forget it), but in the end, Nginx will route (proxy) all traffic from port 443 to the different containers, using "location" directives and "proxy_pass".

Before I miss the question / problem altogether, mking false assumptions, here's a question:

`So, I got nginx set to port 4321` What do you mean by that? How? Reverse proxy with proxy_pass? And the other two? Is that a separate Nginx that's outside docker?

Best would be to post the Nginx config file(s).

Cheers!

**Comment by otomay** [comment]
hey @agrimpelhuber, firstly thanks for trying to help, apreciate it!

About nginx:

> Most important: In the end, Nginx will serve all three containers (App, Websocket and Storage) **on the same port 443, under the same domain, with the same TLS certificate**

Ok, I'm doing that way, but with different subdomains:

- https://excalidraw.mydomain.com.br
- https://excalidrawbd.mydomain.com.br
- https://excalidrawws.mydomain.com.br

Not going to work that way?

> so they'll be all in the same Nginx "server" section.

Not doing that (checked the files). The frontend creates 1 .conf for each proxy host that I add.

Also I use the front end, so I got no experience at editing the files at all, but I can try if is imposible to do with the frontend.

> `So, I got nginx set to port 4321` What do you mean by that? How? Reverse proxy with proxy_pass? And the other two? Is that a separate Nginx that's outside docker?

I mean that I add a new proxy host from `localhost` port `4321` to `https://excalidraw.mydomain.com.br`

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/4e80e586-ea23-4279-be1a-92b68d016ac4)

SSL Section (same certificate for everything)

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/1e4a2130-3f79-4d44-b214-61622c46455c)

And I got 3 of those. One for each port:

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/55252961-06f8-49ab-918a-aca3488669a7)

I'm going to share the .conf file of the 4321 port:

```

# ------------------------------------------------------------
# excalidraw.mydomain.com.br
# ------------------------------------------------------------


server {
  set $forward_scheme http;
  set $server         "10.0.0.217";
  set $port           4321;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;


  server_name excalidraw.mydomain.com.br;


  # Custom SSL
  ssl_certificate /data/custom_ssl/npm-6/fullchain.pem;
  ssl_certificate_key /data/custom_ssl/npm-6/privkey.pem;



# Asset Caching
  include conf.d/include/assets.conf;


  # Block Exploits
  include conf.d/include/block-exploits.conf;



  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;





    # Force SSL
    include conf.d/include/force-ssl.conf;




proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


  access_log /data/logs/proxy-host-17_access.log proxy;
  error_log /data/logs/proxy-host-17_error.log warn;







  location / {





  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;






    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;


    # Proxy!
    include conf.d/include/proxy.conf;
  }


  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

So, based on this, I think I can also edit the .conf files like you said. What do you think?

**Comment by agrimpelhuber** [comment]
@otomay , I'm not familiar with that frontend. I guess we'll find out whether that interface will be able to actually configure Nginx in the way that I imagine will work. Otherwise, you might have to meddle with the Config Files directly.

I'm not sure whether the whole thing might work with 3 subdomains as well. In my experience, using only onesubdomain, and having the reverse proxy divide the traffic to the 3 container **by path** (/, /socket.io, /api/v2) is more robust, because  you don't have to deal with cross-origin stuff in the web client.

Most of all: What is the 10.0.0.217 IP you are using? Is that the IP of your server? Is Nginx running on the same server?

Cheers!

**Comment by alswl** [comment]
@agrimpelhuber
Good job, I will consider to provide the choice to use the same domains.

Thea reason for using different domain is: In my use case, different workloads have different services(svc), and the headless domain is different. And maybe in the the future, the 3 apps may using the same and conflicts path.

> Any plans to update to the newest version

This project is nearly gluewater for 3 projects. I will update after the upstream project upgraded, and I' avoid invented anything new.

@otomay the explanation of the env vars, maybe you should look at he official upstream project.

**Comment by otomay** [comment]
@agrimpelhuber Okay, let`s try

> Most of all: What is the 10.0.0.217 IP you are using? Is that the IP of your server? Is Nginx running on the same server?

It's a local IP. Yes, it's all running on the same server.

---

So, here is the diferences I found in my files vs yours:

**excalidraw.env.production**
```
REACT_APP_BACKEND_V2_GET_URL=https://excalidraw.mydomain.com/api/v2/
REACT_APP_BACKEND_V2_POST_URL=https://excalidraw.mydomain.com/api/v2/post/
```
Mine was with the "test" thing. Didn't know I had to change. Changed, but got the same error.

**Docker-compose:**
```
    environment: # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
      - PORT=8080
```

Besides the fact you're not using ports directives...
Mine was the same of the ports 8081:8081 / 8081; So I tried to change the PORT to 4321, but an error showed about no being able to access the bd, so I went back to 8081.

---

> For you, it's probably more likely you map the 3 (4, if you include redis) to "ports" 8080, 8081, 8082 and 6379 on the host (make sure to secure them in the firewall) by uncommenting the "ports" directives below, and then do all the routing / proxying via "localhost:port".

Yes, I'm doing this way. Redis is on mysql;

When you access `https://excalidraw.mydomain.com/api/v2/` on your browser, are you able to see something that indicates that is working?

I got this:

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/52e6da5d-9797-45a6-b3d0-785d3d064ced)

I still thinking that this is the problem :S

---

But anyways. Tried to do as you sugested too:

(Never saw this tab on frontend lol hahaha)
![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/24f914e6-b842-45b3-b8a6-a27bcf49971b)

Edited .env to use the same subdomain and the dockercompose pointing to a specific network (although this was already happening, bc the mount command created a new network called excalidraw-collaboration_default).

Tried leaving the ports commented, but it didn't go well.
With the same configuration I was using for ports, it goes a bit better. Stopped getting websocket error, but still with the api error (I think it's a evolution, right? ehehehe but colaboration still not working (っ˘̩╭╮˘̩)っ)

![image](https://github.com/alswl/excalidraw-collaboration/assets/54224340/3be3140a-3b86-4b99-95d4-1cf8654ffc36)

Still getting error 404 on https://excalidraw.mydomain.com/api/v2/

**Comment by agrimpelhuber** [comment]
> @agrimpelhuber Good job, I will consider to provide the choice to use the same domains.
> 
@alswl , I think it's fine the way it is from a configuration. No trouble entering the same domain 3 or four times, and having the flexibility to offload to 3 servers / services directly is a nice feature.

It may, however, cause cross-domain trouble for some set-ups, so I like to keep things simple until they run, and they build up from that, a load-balancing set-up for example.

**Comment by agrimpelhuber** [comment]
@otomay , sorry for the late answer. The server is in the office and running on an internal network (the whole point of having it self-hosted), so I need to find time in the office to check things.

**Comment by agrimpelhuber** [comment]
@otomay , I set up a local Nginx-based installation that works. The only thing that differs from you setup appearantly is the fact that i'm running nginx inside a container as well. That makes it easier for me to route traffic between containers. I'm afraid that I won't be able to install Nginx on the host machine. After having discovered the magic of micro services, my host machines only run the bare minimum. Docker, firewall, nothing else.

docker-compose.yaml:

```
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  frontend:
    image: excalidraw:v0.1.0-9c3a908
    container_name: frontend
#    ports:
#      - 8080:80

  storage:
    image: excalidraw-storage-backend:v0.1.0-9c3a908
    container_name: storage
    restart: always
    environment: # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
      - PORT=8081
#    ports:
#      - 8081:8081

  room:
    image: excalidraw-room:v0.1.0-9c3a908
    container_name: room
#    ports:
#      - 8082:80


```
As you can see, only Nginx needs port to the outside. The storage traffic (and the traffic to and from a database) ist routed inside the docker bridge network all containers are attached to. Here is the nginx "default conf" that is being mapped into the nginx container using the "volumes" directive. It's in the same place as docker-compose.yaml:

```

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /socket.io {
        proxy_pass http://room;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /api/v2 {
        proxy_set_header Host $host;
        proxy_pass http://storage:8081;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://frontend;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

```
Of course, the whole TLS stuff (host name, certificates, port 443 instead of 80, logging ...) is missing, but this one runs on http://localhost flawlessly, so you should be able to start from here. Note that the proxy_passes use the internal docker service names as host names.

Here's the excalidraw.env.production

```
REACT_APP_BACKEND_V2_GET_URL=http://localhost/api/v2/
REACT_APP_BACKEND_V2_POST_URL=http://localhost/api/v2/post/

REACT_APP_LIBRARY_URL=https://libraries.excalidraw.com
REACT_APP_LIBRARY_BACKEND=https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries

REACT_APP_HTTP_STORAGE_BACKEND_URL=http://localhost/api/v2
REACT_APP_STORAGE_BACKEND=http

REACT_APP_PORTAL_URL=
# Fill to set socket server URL used for collaboration.
# Meant for forks only: excalidraw.com uses custom REACT_APP_PORTAL_URL flow
REACT_APP_WS_SERVER_URL=http://localhost

REACT_APP_FIREBASE_CONFIG='{}'

# production-only vars
REACT_APP_GOOGLE_ANALYTICS_ID=foo

REACT_APP_PLUS_APP=https://app.excalidraw.com

```
Don't know whether you have to set REACT_APP_BACKEND*, but it doesn't hurt, either.

**Comment by otomay** [comment]
can't get to work :-(

if I came up with something I let you guys know here.
still thinking about how to test the api

**Comment by agrimpelhuber** [comment]
@otomay , I'd like to help you (and others with the same problems as well), but I'm at a loss on where to start the diagnosis or your problems. Maybe we'll start at the basics, if you want:

- Where does your machine live - at a hosting service? Is it shared webspace, a virtual server?
- The IP 10.0.0.217 is the public IP of that machine? Of that machine alone?
- Where does the Nginx GUI come from that you showed - is that some sort of additional software, of did you install it?
- I assume you have shell access to the (Linux?) system?
- How do you register your Domains? Get Certificates?

Don't need to know your specific provider, products etc., just get a rough idea.

On one of the previous questions: As far as I can tell, a get to a room URL on the API **can** actually create a 404 error. The reason, presumably: The web based client creates a new room ID when a session is started, and tries to GET the room (in case it's already there, resuming a previous session). Only if a 404 is returned, the client starts writing a new room, and following GETs succeed. So every time I start a new collaboration session, my console shows one 404.

**Comment by otomay** [comment]
@agrimpelhuber Sorry about the delay, my vacation is over (っ˘̩╭╮˘̩)っ



> * Where does your machine live - at a hosting service? Is it shared webspace, a virtual server?

It's a VPS. Running ubuntu 22.04 - ARM architeture. OCI.
> * The IP 10.0.0.217 is the public IP of that machine? Of that machine alone?

It's the local IP. All services are in the same machine.
> * Where does the Nginx GUI come from that you showed - is that some sort of additional software, of did you install it?

I really don't know how to answer that, cuz it's my first and only time using nginx. I use these images:

image: jc21/nginx-proxy-manager:latest
image: crowdsecurity/crowdsec:v1.4.1

> * I assume you have shell access to the (Linux?) system?

Yes, SSH and RDP if necessary.
> * How do you register your Domains? Get Certificates?

My domain is bought from godaddy. I use cloudflare for ddns (sub-domains) and certificate (singular).

I told you about the providers, products, etc, cuz maybe someone shows with the same doubts thinking that something their using is not compatible.

> Only if a 404 is returned, the client starts writing a new room, and following GETs succeed. So every time I start a new collaboration session, my console shows one 404.

Oh I see, it makes sense. I was being dumb. I saw the error and didn't test again. Before (with the websocket error) I was able to draw in the room that was created, but if I open the link in a private tab, the draw was not being mirrored. So, reading your comment, I give it a try and... yes, it's working (✿◠‿◠). It mirros on another devices.

So, your sugestion worked! What I did, starting after "But anyways. Tried to do as you sugested too:" worked! https://github.com/alswl/excalidraw-collaboration/issues/22#issuecomment-1677504305

Thank you very much!

**Comment by agrimpelhuber** [comment]
@otomay, concerning your last comment: Is everything working now? Collaboration (using websocket / room) and persistence (using storage)?

**Comment by otomay** [comment]
Exactly! All working just fine. I just did tests tho (rebooting the machine, stoping containers, etc). Not using oficially for now, but soon.

Should I close the issue?

**Comment by agrimpelhuber** [comment]
I think you can consider closing it - there's both information on how to diagnose this, and lots of hints for solution. However, I strongly suggest you should consider Traefik some time :-)

**Comment by otomay** [comment]
Sure, thanks!!!

If anyone needs help with it, don't hesitate to mention (✿◠‿◠)

**Comment by maurerle** [comment]
For everyone struggling to set this up using nginx:
These are the instructions which worked as of today to deploy to draw.example.com:

<details>
<summary>Nginx config</summary>

```
server {
    listen 443 ssl http2;
    server_name draw.example.com;

    # Proxy configuration
    location / {
        proxy_pass http://127.0.0.1:9013/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /storage/ {
        proxy_pass http://127.0.0.1:9014/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:9015;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }

    # Adjust client_max_body_size as needed
    client_max_body_size 40M;
}
```

</details>

Then using the following docker-compose.yml

<details>
<summary>compose.yml</summary>

```
services:
  app:
    image: alswl/excalidraw:v0.17.3-fork-b1
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=https://${ROOM_HOST}/
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://${STORAGE_BACKEND_HOST}/api/v2
      - VITE_APP_STORAGE_BACKEND=http
      - VITE_APP_DISABLE_TRACKING=true
      - PUBLIC_URL=https://${APP_HOST}
    ports:
    - "9013:80"

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: unless-stopped
    environment:
      - STORAGE_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
    ports:
      - "9014:8080"

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    restart: unless-stopped
    ports:
      - "9015:80"

  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ${DB_VOLUME_PATH}:/data/db
    user: "1000"
```

</details>

with the following .env file:

```
APP_HOST=draw.example.com
ROOM_HOST=draw.example.com
STORAGE_BACKEND_HOST=draw.example.com/storage

DB_USER=mydbuser
DB_PASS=mydbpass
DB_VOLUME_PATH=./mongo-data
```
