### ISSUE TITLE
通过docker-compose.yaml配置excalidraw环境

### ISSUE THREAD

**Issue by yinhuihe** [alswl/excalidraw-collaboration#25]
大佬好！
可不可以通过docker-compose.yaml来配置excalidraw环境变量，这样方便在不同的环境部署，不用重复构建，下面是我的yaml，我这样写了，但是没有用，请大佬解惑，谢谢！
```
services:
  frontend:
    image: excalidraw:v0.1.0-5b2dbad-dirty
    environment:
      - REACT_APP_BACKEND_V2_GET_URL=https://draw.gc-boy.com/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=https://draw.gc-boy.com/api/v2/post/
      - REACT_APP_LIBRARY_URL=https://libraries.excalidraw.com
      - REACT_APP_LIBRARY_BACKEND=https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      - REACT_APP_HTTP_STORAGE_BACKEND_URL=https://draw.gc-boy.com/api/v2
      - REACT_APP_STORAGE_BACKEND=http
      - REACT_APP_PORTAL_URL=null
      - REACT_APP_WS_SERVER_URL=https://draw.gc-boy.com
      - REACT_APP_FIREBASE_CONFIG="{}"
      - REACT_APP_GOOGLE_ANALYTICS_ID=foo
      - REACT_APP_PLUS_APP=https://app.excalidraw.com
    ports:
      - 80:80

  storage:
    image: excalidraw-storage-backend:v0.1.0-5b2dbad-dirty
    restart: always
    environment: # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
      - PORT=8081
    ports:
      - 8081:8081

  room:
    image: excalidraw-room:v0.1.0-5b2dbad-dirty
    ports:
      - 8082:80
```
