### ISSUE TITLE
FirebaseError: "projectId" not provided in firebase.initializeApp.

### ISSUE THREAD

**Issue by zhangyuning0921** [alswl/excalidraw-collaboration#59]
<img width="1697" alt="截屏2024-03-27 17 32 08" src="https://github.com/alswl/excalidraw-collaboration/assets/148776283/9efe5fc0-8a20-40a7-882c-789d05a6fe3d">

```
# sample comes from https://github.com/docker/awesome-compose
# https://github.com/alswl/excalidraw-collaboration/tree/master
#
version: "3"
services:
  frontend:
    image: alswl/excalidraw:v0.17.3-fork-b1
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://whiteboard1.test.com/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=https://whiteboard1.test.com/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=https://whiteboard2.test.com
      - VITE_APP_FIREBASE_CONFIG={}
      # alswl'fork env
      # forked excalidraw can use env https://github.com/alswl/excalidraw/pull/5
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://whiteboard1.test.com/api/v2
      - VITE_APP_STORAGE_BACKEND=https
    ports:
      - 3010:80

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: always
    environment: # docs https://github.com/alswl/excalidraw-storage-backend#environement-variables
      - PORT=8081
    ports:
      - 3011:8081

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    ports:
      - 3012:80
```

对应的 npm 的映射我也做好了，但是当我点击协作的时候就会出现上图所示的错误
