### ISSUE TITLE
服务器上部署发现问题

### ISSUE THREAD

**Issue by code-lixm** [alswl/excalidraw-collaboration#63]
我现在将三个端口统一从一个域名下转发，如下
![image](https://github.com/alswl/excalidraw-collaboration/assets/42863578/8e95e5c3-673e-4eeb-b8e6-3282dbd5faef)
现在发现一个奇怪的现象：
每次普通刷新：
![Uploading image.png…]()
控制台打印的变量都不是设置的变量
![Uploading image.png…]()
然后强制刷新再打印
![image](https://github.com/alswl/excalidraw-collaboration/assets/42863578/8e95e5c3-673e-4eeb-b8e6-3282dbd5faef)
但是config.ts访问还是访问不到，导致走默认firebase的逻辑，请有时间看一下

**Comment by ajf12f** [comment]
清理缓存，或者换个浏览器再测

**Comment by majunze2001** [comment]
On Ubuntu 22.04.5 with Docker version 27.4.1, the environment variables weren't passed in the frontend. Modifying the docker-compose file and the frontend Dockerfile worked.

**Comment by alswl** [comment]
@majunze2001 Can you show me the patch code?

**Comment by majunze2001** [comment]
Sure. Modifications to the `frontend` in the `docker-compose.yaml`:
```
  frontend:
    build:
      context: ./excalidraw
      args:
        VITE_APP_BACKEND_V2_GET_URL: "https://example.com:8081/api/v2/scenes/"
        VITE_APP_BACKEND_V2_POST_URL: "https://example.com:8081/api/v2/scenes/"
        VITE_APP_WS_SERVER_URL: "https://example.com:8082"
        VITE_APP_FIREBASE_CONFIG: "{}"
        # alswl'fork env
        # forked excalidraw can use env https://github.com/excalidraw/pull/5
        VITE_APP_HTTP_STORAGE_BACKEND_URL: "https://example.com:8081/api/v2"
        VITE_APP_STORAGE_BACKEND: "http"
        PUBLIC_URL: "https://example.com"
```
The `excalidraw` directory is cloned from your repo, with the following lines added to the Dockerfile after the base image.
```
ARG VITE_APP_BACKEND_V2_GET_URL
ARG VITE_APP_BACKEND_V2_POST_URL
ARG VITE_APP_WS_SERVER_URL
ARG VITE_APP_FIREBASE_CONFIG
ARG VITE_APP_HTTP_STORAGE_BACKEND_URL
ARG VITE_APP_STORAGE_BACKEND
ARG PUBLIC_URL
```

I am not sure if this is because I'm using arm machines, but anyway, I need to build the images manually. 
The room and storage backend worked out of the box for me. Thank you for the great work!
